name: 'GitHub Storage Download'
description: 'Download a file from a GitHub hosted repository'
author: 'Hans Hübner, Kong Inc.'

inputs:
  repo-path:
    description: 'Repository path in the form <owner>/<repo>/<branch>/<path>'
    required: true
  local-path:
    description: 'Local name of the file, defaults to the path in the repository'
    required: false

runs:
  using: node20
  main: src/download-action.js
